name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us reproduce and fix the issue.

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Can you help fix this?
      description: Let us know if you're able to contribute to the solution
      options:
        - label: I can help implement the fix
        - label: I can help with testing the fix
        - label: I need someone else to fix this

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "When I do X, Y happens instead of Z..."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: What should have happened instead?
      placeholder: "I expected..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened?
      placeholder: "Instead, what happened was..."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain the problem
      placeholder: "Drag and drop images/videos here or paste URLs"

  - type: textarea
    id: environment
    attributes:
      label: 🔧 Environment
      description: Please complete the following information
      placeholder: |
        - OS: [e.g. Windows 11, macOS 13, Ubuntu 22.04]
        - Browser: [e.g. Chrome 118, Firefox 119, Safari 16] (if web-based)
        - Application Version: [e.g. v1.2.3]
        - Rust Version: [e.g. 1.73.0] (if relevant)
        - Other relevant versions: [e.g. egui 0.23.0]
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context about the problem here
      placeholder: "This might be related to..."
