name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us reproduce and fix the issue.

  - type: checkboxes
    id: contribution
    attributes:
      label: Can you help fix this?
      description: Let us know if you're able to contribute to the solution
      options:
        - label: I can help implement the fix
        - label: I can help with testing the fix
        - label: I need someone else to fix this

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "When I do X, Y happens instead of Z..."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please complete the following information
      placeholder: |
        - OS, application version, Rust version, ...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
