name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "triage"]
body:

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Can you help implement this feature?
      options:
        - label: I can contribute to implementing this feature
        - label: I'm willing to help with testing/feedback
        - label: I need someone else to implement this (that's okay too!)

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see
    validations:
      required: true

  - type: textarea
    id: visual-design
    attributes:
      label: How should this feature look and interact with the user?
      description:  You can use https://monodraw.helftone.com/ or https://asciiflow.com/ to make mockups.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: "Any other information that might be helpful..."
