name: test

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest
      - name: Run unit tests
        run: cargo nextest run --workspace --lib
        env:
          CI: 0
          # Disable CI mode to have insta save snapshots to files.
          # See https://github.com/mitsuhiko/insta/issues/344

  offline-integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest
      - name: Run localized integration tests
        run: cargo nextest run -p tgv --test offline_app
        env:
          CI: 0
          # Disable CI mode to have insta save snapshots to files.
          # See https://github.com/mitsuhiko/insta/issues/344
      - name: Show snapshots
        run: |
          shopt -s nullglob
          for file in crates/tgv/src/snapshots/*; do
            echo $file
            cat $file
          done

  network-integration-tests:
    runs-on: ubuntu-latest
    needs: offline-integration-tests
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest
      - name: Run network integration tests
        run: cargo nextest run -p tgv --test online_app --run-ignored ignored-only
        env:
          CI: 0
          # Disable CI mode to have insta save snapshots to files.
          # See https://github.com/mitsuhiko/insta/issues/344
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Format
  #     run: cargo fmt --check
  #   - name: Clippy
  #     run: cargo clippy --
